//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PL.LibroService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LibroService.ILibro")]
    public interface ILibro {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibro/Add", ReplyAction="http://tempuri.org/ILibro/AddResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Autor))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Libro))]
        ML.Result Add(ML.Libro libro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibro/Add", ReplyAction="http://tempuri.org/ILibro/AddResponse")]
        System.Threading.Tasks.Task<ML.Result> AddAsync(ML.Libro libro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibro/Update", ReplyAction="http://tempuri.org/ILibro/UpdateResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Autor))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Libro))]
        ML.Result Update(ML.Libro libro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibro/Update", ReplyAction="http://tempuri.org/ILibro/UpdateResponse")]
        System.Threading.Tasks.Task<ML.Result> UpdateAsync(ML.Libro libro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibro/Delete", ReplyAction="http://tempuri.org/ILibro/DeleteResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Libro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Autor))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        ML.Result Delete(int IdLibro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibro/Delete", ReplyAction="http://tempuri.org/ILibro/DeleteResponse")]
        System.Threading.Tasks.Task<ML.Result> DeleteAsync(int IdLibro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibro/GetAll", ReplyAction="http://tempuri.org/ILibro/GetAllResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Libro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Autor))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        ML.Result GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibro/GetAll", ReplyAction="http://tempuri.org/ILibro/GetAllResponse")]
        System.Threading.Tasks.Task<ML.Result> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibro/GetById", ReplyAction="http://tempuri.org/ILibro/GetByIdResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Libro))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ML.Autor))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        ML.Result GetById(int IdLibro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILibro/GetById", ReplyAction="http://tempuri.org/ILibro/GetByIdResponse")]
        System.Threading.Tasks.Task<ML.Result> GetByIdAsync(int IdLibro);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILibroChannel : PL.LibroService.ILibro, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LibroClient : System.ServiceModel.ClientBase<PL.LibroService.ILibro>, PL.LibroService.ILibro {
        
        public LibroClient() {
        }
        
        public LibroClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LibroClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LibroClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LibroClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ML.Result Add(ML.Libro libro) {
            return base.Channel.Add(libro);
        }
        
        public System.Threading.Tasks.Task<ML.Result> AddAsync(ML.Libro libro) {
            return base.Channel.AddAsync(libro);
        }
        
        public ML.Result Update(ML.Libro libro) {
            return base.Channel.Update(libro);
        }
        
        public System.Threading.Tasks.Task<ML.Result> UpdateAsync(ML.Libro libro) {
            return base.Channel.UpdateAsync(libro);
        }
        
        public ML.Result Delete(int IdLibro) {
            return base.Channel.Delete(IdLibro);
        }
        
        public System.Threading.Tasks.Task<ML.Result> DeleteAsync(int IdLibro) {
            return base.Channel.DeleteAsync(IdLibro);
        }
        
        public ML.Result GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<ML.Result> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public ML.Result GetById(int IdLibro) {
            return base.Channel.GetById(IdLibro);
        }
        
        public System.Threading.Tasks.Task<ML.Result> GetByIdAsync(int IdLibro) {
            return base.Channel.GetByIdAsync(IdLibro);
        }
    }
}
